version: '3'

services:
  db:
    image: mavpks/mysql-server:8.0
  web:
    build: .
    command: ["/bin/bash", "-c","sleep 15 && python manage.py migrate && python manage.py runserver 0.0.0.0:8080"]
    volumes:
      - .:/usr/src/app
    ports:
      - "8080:8080"
    depends_on:
      - db
